apiVersion: apps/v1
kind: Deployment
metadata:
  name: smi-adapter-cpx
  namespace: cpx-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smi-adapter-cpx
  template:
    metadata:
      labels:
        name: smi-adapter-cpx
      annotations:
        sidecar.cpx.io/inject: "false"
    spec:
      serviceAccountName: smi-adapter-cpx
      containers:
        - name: smi-adapter-cpx
          image: layer5/smi-cpx:latest
          command:
          - smi-adapter-cpx
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "smi-adapter-cpx"
