apiVersion: v1
kind: ServiceAccount
metadata:
  name: smi-adapter-cpx
  namespace: cpx-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smi-adapter-cpx
  namespace: cpx-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - smi-adapter-cpx
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - split.smi-spec.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - networking.cpx.io
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smi-adapter-cpx
subjects:
  - kind: ServiceAccount
    name: smi-adapter-cpx
    namespace: cpx-system
roleRef:
  kind: ClusterRole
  name: smi-adapter-cpx
  apiGroup: rbac.authorization.k8s.io